version: "3.7"
services:
  api:
    image: node:14-alpine
    container_name: api-agenda
    restart: always
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3333:3333"
    command: yarn dev
    depends_on:
      - mongo
  mongo:
    container_name: mongo_database
    image: mongo
    ports:
      - "27017:27017"
    restart: always
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongo
  web:
    image: node:14-alpine
    container_name: frontend-agenda
    restart: always
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "8080:8080"
    command: yarn dev
